BASE_URL = 'https://api-dev.canotic.com/v1'
BASE_FOLDER = '~/.canoticapiclient'
COGNITO_REGION = 'us-east-1'
COGNITO_USERPOOL_ID = 'us-east-1_hwjZuxqbI'
COGNITO_CLIENT_ID = '6vt1a0uflonucrknj6sl0q3vc2'